### ISSUE TITLE
Does not work in Router-Outlets

### ISSUE THREAD

**Issue by Ericky14** [NathanaelA/nativescript-platform-css#10]
When using ```/deep/ .ios Button```, I noticed the css only being applied to all page elements except the ones inside the ```<router-outlet>``` in that same page.

Well, I am not entirely sure that is the issue here, but for some reason I am not able to apply the css to the certain elements I need to apply it to. ```/deep/ .ios .option-button``` is not working in my case.

**Comment by NathanaelA** [comment]
Can you try using the `:host` modifier; I was informed recently that it also works.
