### ISSUE TITLE
Webpack with uglify build fails in Angular app

### ISSUE THREAD

**Issue by manojdcoder** [NathanaelA/nativescript-platform-css#12]
```
ERROR in bundle.js from UglifyJs
Unexpected token: name (deviceInfo) [bundle.js:10558,4]
```

**Comment by manojdcoder** [comment]
@NathanaelA I think using `let` breaks UglifyJs, any idea how to fix that?

**Comment by manojdcoder** [comment]
[This](https://github.com/NativeScript/nativescript-angular/issues/1011#issuecomment-333539020) made a fix.

**Comment by prabudevarrajan1** [comment]
Hi @manojdcoder, can you please explain more on this fix
