### ISSUE TITLE
Use :host instead of /deep/

### ISSUE THREAD

**Issue by erkanarslan** [NathanaelA/nativescript-platform-css#14]
Angular isolates component styles from other parts of application. It seems that `/deep/ .ios .class-name` breaks this isolation and styles are applied to other parts of the application as well. I tried `.ios :host .class-name` approach and it seems that this one doesn't break isolation.

It would be better for other users if you change /deep/ example on the read me file to the one with :host.

**Comment by NathanaelA** [comment]
Thank you I'll update the doc's.
