### ISSUE TITLE
.ios/.androidXXX not working on platform.android/ios.css

### ISSUE THREAD

**Issue by iMarwan-k** [NathanaelA/nativescript-platform-css#15]
Hi,

When I place the .androidXXX or .iosXXX classes on platform.android.css or platform.ios.css it doesn't work

app.modules.js
```
var nsPlatformCss = require('nativescript-platform-css');
if(isAndroid){
  nsPlatformCss.sizeGroupings(true);
}

```
platform.android.css
```
.android400 :host #welcomeBtnGrid .primaryBtn {
    font-family: "SF-Pro-Display-Medium";
    font-size: 30;
    width: 315;
    height: 52.42;
}
```

however, if I place the same code on component css class like welcome.android.css it works

Any guess?

**Comment by NathanaelA** [comment]
What is loading `platform.yyyyy.css` --- The plugin itself does not auto-load any css files; so unless you have something importing the css it won't be loaded.

**Comment by iMarwan-k** [comment]
`platform.yyyyy.css` is loaded by NS engine 

https://docs.nativescript.org/angular/tutorial/ng-chapter-2#26-global-css

**Comment by iMarwan-k** [comment]
I just play with it and I found that if you want to use .iosXXX or .androidXXX in app.css or platform.ios.css or platform.android.css don't include :host keyword

for example

platform.android.css
.```
android400 #welcomeBtnGrid .primaryBtn {
    font-family: "SF-Pro-Display-Medium";
    font-size: 30;
    width: 315;
    height: 52.42;
}
```

but if you want to use the same thing in the css file for the component do the following
welcome.android.css

```
android400 :host #welcomeBtnGrid .primaryBtn {
    font-family: "SF-Pro-Display-Medium";
    font-size: 30;
    width: 315;
    height: 52.42;
}
```

**Comment by NathanaelA** [comment]
Ah, didn't know that.  Thanks for the feedback!
