### ISSUE TITLE
Unable to install - getting 'Not Found'

### ISSUE THREAD

**Issue by jdavidbakr** [NathanaelA/nativescript-platform-css#29]
Any ideas?  Here is the command and output:

```
$ tns plugin add @proplugins/nativescript-platform-css
npm ERR! code E404
npm ERR! 404 Not Found: @proplugins/nativescript-platform-css@latest
```

**Comment by NathanaelA** [comment]
Well I would need to see the rest of the error; but my guess is that you do not have the `@proplugins` namespace pointed to the proper package server.     

The command is: 
npm login --registry=https://npm.proplugins.org --scope=@proplugins
And you need to use the username/password you setup for your account.
