### ISSUE TITLE
Does it work with NativeScript 3.0?

### ISSUE THREAD

**Issue by d3mac123** [NathanaelA/nativescript-platform-css#4]
I followed the instructions but the settings/colors are not changing in the OSs. Is this related to NS 3.0?

thanks!
Alex

**Comment by NathanaelA** [comment]
Yes, very few plugins have been converted to be 3.0 compatible yet.  http://plugins.nativescript.rocks actually now has a pull down so you can see plugins that have been tagged as 3.0 compatible

**Comment by d3mac123** [comment]
Thanks Nathanael! Looking forward to use your plugins soon (I've tried to downgrade to 2.5.0 but Android did not allowed me to do so :( )

**Comment by NathanaelA** [comment]
See my blog post: http://fluentreports.com/blog/?p=509

**Comment by theCSSguru** [comment]
Will you get this to work in 3.0? It was so useful pre 3.0, and would love to have this again! Thank you.

**Comment by NathanaelA** [comment]
This is now verified to work in 3.0, with a new feature.
