### ISSUE TITLE
Unfinished description of enhanced modes in README.

### ISSUE THREAD

**Issue by antfarm** [NathanaelA/nativescript-platform-css#7]
The sentence in the description of _Enhanced Modes_ is not finished. Information about size groupings is missing from the README file.

https://github.com/nathanaela/nativescript-platform-css#enhanced-modes
https://github.com/NathanaelA/nativescript-platform-css/blame/master/README.md#L70

**Comment by NathanaelA** [comment]
Thanks, this will be fixed soon.  I just finished updating https://github.com/NathanaelA/Nativescript-globalevents and https://github.com/NathanaelA/NativeScript-platform for v3.x of NativeScript this week -- so this is next in line to be fixed -- and there will be a new feature added to this plugin's enhanced mode and I'll verify the docs get fixed here.  :grinning:

**Comment by NathanaelA** [comment]
Thanks the docs are now fixed on github.  😀
